title: Niranjan Sujay
logo: /Images/nyu pic.JPG
description: I'm a robotics researcher with a Master's in Mechatronics and Robotics from NYU, currently interning at the AI4CE Lab under Dr. Chen Feng. My work focuses on robotic perception and 3D mapping, including projects like MappingNYC, which develops multimodal datasets for urban autonomous navigation. Beyond research, I enjoy mentoring students in robotics, sharing knowledge, and contributing to community STEM education initiatives.
show_downloads: true
theme: jekyll-theme-minimal
